.\" Emacs: -*- nroff -*-
.TH oshfort 1 ""
.SH NAME
\fBoshfort\fP - compile an OpenSHMEM Fortran program
.SH SYNOPSIS
\fBoshfort\fP
[ underlying compiler flags ]
file.f90 [file.f90 ...]
.SH DESCRIPTION
\fBoshfort\fP is a wrapper in the vein of mpif90 that compiles
an OpenSHMEM program.  The wrapper hides implementation
details from the user.
.SH EXAMPLES
The command
.LP
.RS
$ oshfort -g -o foo.exe foo.f90
.RE
.LP
compiles the Fortran source code foo.f90 into the OpenSHMEM executable foo.exe.
.SH SEE ALSO
intro_shmem(3),
oshrun(1),
oshcc(1)
