#!/bin/sh

svn update

rev="`svn info | grep '^Revision:'`"

cat <<EOT    > $1
/*
 * AUTOGENERATED BY make, DO NOT EDIT DIRECTLY
 */

char *
shmem_version(void)
{
  return "Super Happy Fun OpenSHMEM, $rev";
}

#ifdef HAVE_PSHMEM_SUPPORT
#pragma weak pshmem_version = shmem_version
#endif /* HAVE_PSHMEM_SUPPORT */
EOT
