#!/bin/sh

if [ $# -lt 1 ]
then
  echo "Usage: $0 version-source-file"
  exit 1
fi

svn update

rev="`svn info | grep '^Revision:'`"

cat <<_EOT_    > $1
/*
 * AUTOGENERATED BY make, DO NOT EDIT DIRECTLY
 */

#include "utils.h"

char *
pshmem_version(void)
{
  INIT_CHECK();
  return "Super Happy Fun OpenSHMEM, $rev";
}

#pragma weak shmem_version = pshmem_version
_EOT_
