/*
 * AUTOGENERATED BY make, DO NOT EDIT DIRECTLY
 */

#include "utils.h"

char *
pshmem_version(void)
{
  INIT_CHECK();
  return "Super Happy Fun OpenSHMEM, Revision: 1613";
}

#pragma weak shmem_version = pshmem_version
